Update styles.css (STYLEINT issues)
Corrections for STYLEINT linter issues:

assets/css/style.css
   5:3   ✖  Unexpected empty line before declaration   declaration-empty-line-before
   7:3   ✖  Unexpected empty line before declaration   declaration-empty-line-before
  18:3   ✖  Unexpected empty line before declaration   declaration-empty-line-before
  39:3   ✖  Unexpected empty line before declaration   declaration-empty-line-before
  49:3   ✖  Unexpected empty line before declaration   declaration-empty-line-before
  49:16  ✖  Unexpected missing generic font family     font-family-no-missing-generic-family-keyword
  56:3   ✖  Unexpected empty line before declaration   declaration-empty-line-before
  60:1   ✖  Expected empty line before rule            rule-empty-line-before
  65:3   ✖  Unexpected empty line before declaration   declaration-empty-line-before
  65:16  ✖  Unexpected missing generic font family     font-family-no-missing-generic-family-keyword
  72:3   ✖  Unexpected empty line before declaration   declaration-empty-line-before
  82:3   ✖  Unexpected empty line before declaration   declaration-empty-line-before
  82:16  ✖  Unexpected missing generic font family     font-family-no-missing-generic-family-keyword
  90:3   ✖  Unexpected empty line before declaration   declaration-empty-line-before
 101:3   ✖  Unexpected empty line before declaration   declaration-empty-line-before
 104:3   ✖  Unexpected empty line before declaration   declaration-empty-line-before

Error: Process completed with exit code 2.